#ifdef RGB_MATRIX_ENABLE
  #define ENABLE_RGB_MATRIX_SOLID_COLOR
  
  #define RGB_MATRIX_DEFAULT_HUE 0
  #define RGB_MATRIX_DEFAULT_SAT 255
  #define RGB_MATRIX_DEFAULT_VAL 64

  #define RGB_MATRIX_TIMEOUT 120000
  #define RGB_MATRIX_SLEEP
#endif
